package its340project;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import java.awt.Color;

public class GeneralMedical extends javax.swing.JFrame {

    public int PatientID;
    public String PatientName;
    
    public GeneralMedical() {
        initComponents();
    }
    public GeneralMedical(int patientID, String name)
    {
        initComponents();
        PatientID = patientID;
        PatientName = name;
        
        lPatientID.setText(Integer.toString(PatientID));
        lName.setText(PatientName);
        
        String connString = DBUtils.getConnString();
        Patient patient = new Patient();
        patient = DBUtils.getGenMed(PatientID, connString);
        
        if(patient != null)
        {
            tGeneralMedicalHistoryID.setText(Integer.toString(patient.getGeneralMedicalHistoryID()));
            tPatientID.setText(Integer.toString(patient.getPatientID()));
            tTobacco.setText(patient.getTobacco());
            tTobaccoQuantity.setText(patient.getTobaccoQuantity());
            tTobaccoDuration.setText(patient.getTobaccoduraton());
            tAlcohol.setText(patient.getAlcohol());
            tAlcoholQuantity.setText(patient.getAlcoholQuantity());
            tAlcoholDuration.setText(patient.getAlcoholduration());
            tDrug.setText(patient.getDrug());
            tDrugType.setText(patient.getDrugType());
            tDrugDuration.setText(patient.getDrugduration());
            tBloodType.setText(patient.getBloodType());
            tRHFactor.setText(patient.getRh());

        }
        else
        {
            System.out.println("Patient object is null. No values were loaded from database");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tGeneralMedicalHistoryID = new javax.swing.JTextField();
        tPatientID = new javax.swing.JTextField();
        tTobacco = new javax.swing.JTextField();
        tTobaccoQuantity = new javax.swing.JTextField();
        tTobaccoDuration = new javax.swing.JTextField();
        tAlcohol = new javax.swing.JTextField();
        tAlcoholQuantity = new javax.swing.JTextField();
        tAlcoholDuration = new javax.swing.JTextField();
        tDrug = new javax.swing.JTextField();
        tDrugType = new javax.swing.JTextField();
        tDrugDuration = new javax.swing.JTextField();
        tBloodType = new javax.swing.JTextField();
        tRHFactor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        bNew = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bInterview = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bSelection = new javax.swing.JButton();
        bDemos = new javax.swing.JButton();
        bGenMed = new javax.swing.JButton();
        bFamHist = new javax.swing.JButton();
        bAlgHist = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        lPatientID = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("General Medical History ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Patient ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tobacco:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tobacco Quantity:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tobacco Duration:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Alcohol:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Alcohol Quantity:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Alcohol Duration:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Drug:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Drug Type:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Drug Duration:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Blood Type:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("RH Factor:");

        tGeneralMedicalHistoryID.setEditable(false);
        tGeneralMedicalHistoryID.setBackground(new java.awt.Color(153, 153, 153));

        tPatientID.setEditable(false);
        tPatientID.setBackground(new java.awt.Color(153, 153, 153));

        tTobacco.setEditable(false);
        tTobacco.setBackground(new java.awt.Color(153, 153, 153));

        tTobaccoQuantity.setEditable(false);
        tTobaccoQuantity.setBackground(new java.awt.Color(153, 153, 153));

        tTobaccoDuration.setEditable(false);
        tTobaccoDuration.setBackground(new java.awt.Color(153, 153, 153));

        tAlcohol.setEditable(false);
        tAlcohol.setBackground(new java.awt.Color(153, 153, 153));

        tAlcoholQuantity.setEditable(false);
        tAlcoholQuantity.setBackground(new java.awt.Color(153, 153, 153));

        tAlcoholDuration.setEditable(false);
        tAlcoholDuration.setBackground(new java.awt.Color(153, 153, 153));

        tDrug.setEditable(false);
        tDrug.setBackground(new java.awt.Color(153, 153, 153));

        tDrugType.setEditable(false);
        tDrugType.setBackground(new java.awt.Color(153, 153, 153));

        tDrugDuration.setEditable(false);
        tDrugDuration.setBackground(new java.awt.Color(153, 153, 153));

        tBloodType.setEditable(false);
        tBloodType.setBackground(new java.awt.Color(153, 153, 153));

        tRHFactor.setEditable(false);
        tRHFactor.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tGeneralMedicalHistoryID)
                    .addComponent(tPatientID)
                    .addComponent(tTobacco)
                    .addComponent(tTobaccoQuantity)
                    .addComponent(tTobaccoDuration)
                    .addComponent(tAlcohol)
                    .addComponent(tAlcoholQuantity)
                    .addComponent(tAlcoholDuration)
                    .addComponent(tDrug)
                    .addComponent(tDrugType)
                    .addComponent(tDrugDuration)
                    .addComponent(tBloodType)
                    .addComponent(tRHFactor, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tGeneralMedicalHistoryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tTobacco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tTobaccoQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tTobaccoDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tAlcoholQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tAlcoholDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tDrugType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tDrugDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tRHFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        bNew.setText("New");
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSave)
                    .addComponent(bNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNew)
                    .addComponent(bEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bDelete))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        bInterview.setText("Start Automated Interview");
        bInterview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInterviewActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        bSelection.setText("Patient Selection");
        bSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelectionActionPerformed(evt);
            }
        });

        bDemos.setText("Patient Demographics");
        bDemos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDemosActionPerformed(evt);
            }
        });

        bGenMed.setText("Gen Med History");
        bGenMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenMedActionPerformed(evt);
            }
        });

        bFamHist.setText("Family History");
        bFamHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFamHistActionPerformed(evt);
            }
        });

        bAlgHist.setText("Allergy History");
        bAlgHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlgHistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDemos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bGenMed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFamHist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAlgHist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(bSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bDemos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bGenMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bFamHist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAlgHist)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel23.setText("PatientID: ");

        lPatientID.setText("Value Not Loaded...");

        jLabel24.setText("Patient Name:");

        lName.setText("Value Not Loaded...");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPatientID)
                .addGap(33, 33, 33)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(lName)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bInterview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(bInterview)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewActionPerformed
        List<JTextField> textFields = new ArrayList<>();
        textFields.add(tTobacco);
        textFields.add(tTobaccoQuantity);
        textFields.add(tTobaccoDuration);
        textFields.add(tAlcohol);
        textFields.add(tAlcoholQuantity);
        textFields.add(tAlcoholDuration);
        textFields.add(tDrug);
        textFields.add(tDrugType);
        textFields.add(tDrugDuration);
        textFields.add(tBloodType);
        textFields.add(tRHFactor);

        for(JTextField tf : textFields)
        {
            tf.setText(null);
            tf.setEditable(true);
            tf.setBackground(Color.white);
        }
        tPatientID.setEditable(false);
        tPatientID.setText(Integer.toString(PatientID));
        tGeneralMedicalHistoryID.setEditable(false);
        
    }//GEN-LAST:event_bNewActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        List<JTextField> textFields = new ArrayList<>();
        textFields.add(tTobacco);
        textFields.add(tTobaccoQuantity);
        textFields.add(tTobaccoDuration);
        textFields.add(tAlcohol);
        textFields.add(tAlcoholQuantity);
        textFields.add(tAlcoholDuration);
        textFields.add(tDrug);
        textFields.add(tDrugType);
        textFields.add(tDrugDuration);
        textFields.add(tBloodType);
        textFields.add(tRHFactor);
        for(JTextField tf: textFields)
        {
            tf.setEditable(true);
            tf.setBackground(Color.white);
        }
        tPatientID.setEditable(false);
    }//GEN-LAST:event_bEditActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        String connString = DBUtils.getConnString();
    Patient saveP = new Patient(
    Integer.parseInt(tPatientID.getText()),
    Integer.parseInt(tGeneralMedicalHistoryID.getText()),
        tTobacco.getText(),
        tTobaccoQuantity.getText(),
        tTobaccoDuration.getText(),
        tAlcohol.getText(),
        tAlcoholQuantity.getText(),
        tAlcoholDuration.getText(),
        tDrug.getText(),
        tDrugType.getText(),
        tDrugDuration.getText(),
        tBloodType.getText(),
        tRHFactor.getText()
    );

    DBUtils.savePatientDemo(saveP, connString);
    
    List<JTextField> textFields = new ArrayList<>();
    textFields.add(tTobacco);
    textFields.add(tTobaccoQuantity);
    textFields.add(tTobaccoDuration);
    textFields.add(tAlcohol);
    textFields.add(tAlcoholQuantity);
    textFields.add(tAlcoholDuration);
    textFields.add(tDrug);
    textFields.add(tDrugType);
    textFields.add(tDrugDuration);
    textFields.add(tBloodType);
    textFields.add(tRHFactor);

    for (JTextField tf : textFields) 
    {
        tf.setEditable(false);
        tf.setBackground(Color.gray);
    }


    }//GEN-LAST:event_bSaveActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        String connString = DBUtils.getConnString();
        DBUtils.deleteGenMed(Integer.parseInt(tPatientID.getText()), connString);
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bInterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInterviewActionPerformed
        DecisionTree genmedInterview = new DecisionTree();
        int GeneralMedicalHistoryID;
//        genmedInterview.createRoot(1, "Does the patient use tobacco?");
//        
//        genmedInterview.insertNoNode(1, 2, "Does the patient use alcohol?");
//        genmedInterview.insertNoNode(2, 4, "Does the patient use drugs?");
//        genmedInterview.insertNoNode(4, 7, "Input: What is the patient's blood type?");
//        
//        
//        genmedInterview.insertYesNode(1, 3, "Input: What is the quantity of tobacco the patient uses?");
//        genmedInterview.insertYesNode(3, 6, "Input: What is the duration of the patient's use of tobacco?");
//        genmedInterview.insertYesNode(6, 2, "Does thes patient use alcohol?");
//        genmedInterview.insertYesNode(2, 5, "Input: What is the quantity of alcohol the patient uses?");
//        genmedInterview.insertYesNode(5, 9, "Input: What is the duration of the patient's use of alcohol?");
//        genmedInterview.insertYesNode(9, 4, "Does the patient use drugs?");
//        genmedInterview.insertYesNode(4, 8, "Input: What is the type of drug the patient has been using?");
//        genmedInterview.insertYesNode(8, 11, "Input: What is the duration of the patient's use of drugs?");
//        genmedInterview.insertYesNode(11, 7, "Input: What is the patient's blood type?");
//        genmedInterview.insertYesNode(7, 10, "Input: What is the patient's RH Factor?");
//        genmedInterview.insertYesNode(7, 10, "Interview is complete, thank you!");
        

        genmedInterview.createRoot(1, "Does the patient use tobacco?");

        // Insert nodes
        genmedInterview.insertYesNode(1, 2, "Input: What is the quantity of tobacco the patient uses?");
        genmedInterview.insertYesNode(2, 4, "Input: What is the duration of the patient's use of tobacco?");
        genmedInterview.insertYesNode(4, 6, "Does the patient use alcohol?");
        genmedInterview.insertYesNode(6, 8, "Input: What is the quantity of alcohol the patient uses?");
        genmedInterview.insertYesNode(8, 10, "Input: What is the duration of the patient's use of alcohol?");
        genmedInterview.insertYesNode(10, 12, "Does the patient use drugs?");
        genmedInterview.insertYesNode(12, 14, "Input: What is the type of drug the patient has been using?");
        genmedInterview.insertYesNode(14, 16, "Input: What is the duration of the patient's use of drugs?");
        genmedInterview.insertYesNode(16, 18, "Input: What is the patient's blood type?");
        genmedInterview.insertYesNode(18, 20, "Input: What is the patient's RH Factor?");

        
        genmedInterview.insertNoNode(1, 3, "Does the patient use drugs?");
        genmedInterview.insertNoNode(3, 5, "Input: What is the patient's blood type?");
        genmedInterview.insertYesNode(5, 7, "Input: What is the patient's RH Factor?");
        genmedInterview.insertNoNode(12, 5, "Input: What is the patient's blood type?");
        genmedInterview.insertNoNode(6, 3, "Does the patient use drugs?");
        genmedInterview.insertNoNode(3, 5, "Input: What is the patient's blood type?");
        genmedInterview.insertYesNode(5, 7, "Input: What is the patient's RH Factor?");
        



        genmedInterview.queryTree(genmedInterview.getRoot());
        List<String> interviewAnswers = new ArrayList<>();
        List<String> interviewQuestions = new ArrayList<>();
        interviewAnswers = genmedInterview.getAnswers();
        interviewQuestions = genmedInterview.getQuestions();
        if(tGeneralMedicalHistoryID.getText().isEmpty())
        {
            GeneralMedicalHistoryID = 999999;
        }
        else
        {
            GeneralMedicalHistoryID = Integer.parseInt(tGeneralMedicalHistoryID.getText());
        }
        Patient interview = new Patient(PatientID, GeneralMedicalHistoryID, interviewAnswers.get(0), interviewAnswers.get(1),interviewAnswers.get(2),interviewAnswers.get(3),interviewAnswers.get(4),
        interviewAnswers.get(5),interviewAnswers.get(6),interviewAnswers.get(7),interviewAnswers.get(8),interviewAnswers.get(9),interviewAnswers.get(10));
        DBUtils.saveGenMed(interview, DBUtils.getConnString());
        genmedInterview.logInterview(interview, genmedInterview);
        
        for(String item: interviewAnswers)
        {
            System.out.println(item);
        }
        
        if(interviewAnswers.size() == 2)
        {
            System.out.println("This is the left side of the tree where its less work");
        }
        else if (interviewAnswers.size() == 3)
        {
            System.out.println("This is the right side of the tree where you will iterate through to get the values for the left side");
        }
        
        GeneralMedical gm = new GeneralMedical(PatientID, PatientName);
        gm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_bInterviewActionPerformed

    private void bSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelectionActionPerformed
        PatientSelection ps = new PatientSelection();
        ps.setVisible(true);
        dispose();
    }//GEN-LAST:event_bSelectionActionPerformed

    private void bDemosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDemosActionPerformed
        PatientDemographics dp = new PatientDemographics(PatientID);
        dp.setVisible(true);
        dispose();
    }//GEN-LAST:event_bDemosActionPerformed

    private void bGenMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenMedActionPerformed
        GeneralMedical gm = new GeneralMedical(PatientID, PatientName);
        gm.setVisible(true);
        dispose();
    }//GEN-LAST:event_bGenMedActionPerformed

    private void bFamHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFamHistActionPerformed
        FamilyHistory fh = new FamilyHistory(PatientID, PatientName);
        fh.setVisible(true);
        dispose();
    }//GEN-LAST:event_bFamHistActionPerformed

    private void bAlgHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlgHistActionPerformed
        AllergyHistory ah = new AllergyHistory(PatientID, PatientName);
        ah.setVisible(true);
        dispose();
    }//GEN-LAST:event_bAlgHistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralMedical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlgHist;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bDemos;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bFamHist;
    private javax.swing.JButton bGenMed;
    private javax.swing.JButton bInterview;
    private javax.swing.JButton bNew;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPatientID;
    private javax.swing.JTextField tAlcohol;
    private javax.swing.JTextField tAlcoholDuration;
    private javax.swing.JTextField tAlcoholQuantity;
    private javax.swing.JTextField tBloodType;
    private javax.swing.JTextField tDrug;
    private javax.swing.JTextField tDrugDuration;
    private javax.swing.JTextField tDrugType;
    private javax.swing.JTextField tGeneralMedicalHistoryID;
    private javax.swing.JTextField tPatientID;
    private javax.swing.JTextField tRHFactor;
    private javax.swing.JTextField tTobacco;
    private javax.swing.JTextField tTobaccoDuration;
    private javax.swing.JTextField tTobaccoQuantity;
    // End of variables declaration//GEN-END:variables
}
