package its340project;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class PatientSelection extends javax.swing.JFrame {

    
    
    /**
     * Creates new form PatientSelection
     */
    public PatientSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tbLastName = new javax.swing.JTextField();
        btnShowData = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PatientID", "Patient Last Name", "Patient First Name", "Patient Mobile Phone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tbLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLastNameActionPerformed(evt);
            }
        });

        btnShowData.setText("Show Data");
        btnShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDataActionPerformed(evt);
            }
        });

        jLabel2.setText("Last Name:");

        btnContinue.setText("Continue");
        btnContinue.setEnabled(false);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnShowData, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnShowData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnContinue)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbLastNameActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        //Grab PatientID from table and store it.
        
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        if (index >= 0 && model != null) 
        {
            
            String PatientID = (model.getValueAt(index, 0) != null) ? model.getValueAt(index, 0).toString() : ""; 
            int patientID = Integer.parseInt(PatientID);
            PatientDemographics PD = new PatientDemographics(patientID);
            System.out.println(PatientID); // Test to see if code grabbed PatientID
            PD.setVisible(true);
            dispose();
        }
       
        
        
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDataActionPerformed
        Connection conn = null;
        String dbURL = "jdbc:mysql://54.163.48.244:3306/340project?autoreconnect=true&useSSL=false";
        String dbData;
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String query;
            if(!tbLastName.getText().isEmpty())
            {
                query = "SELECT * FROM patienttable WHERE PtLastName = '" + tbLastName.getText() + "'";
            }
            else
            {
                query = "SELECT * FROM patienttable";
            }
            conn = DriverManager.getConnection(dbURL, "programUser", "6wc7#bjx^%LWDkym8vG");
            PreparedStatement statement = conn.prepareStatement(query);
            ResultSet rs = statement.executeQuery();
        
            //test statement to show all data but I dummed it down so it's not a copy/paste of patient demographics
//            DefaultTableModel tbl = new DefaultTableModel(new String[]{"PatientID", "FirstName", "LastName", "PhoneNumber",
//            "PreviousLastName", "HomeAddress", "HomeState", "Country", "Citizenship", "EmergencyPhone", "HomeZip", "HomeCity",
//            "EmailAddress", "SSN", "DOB", "Gender", "EthnicAssociation", "MaritalStatus", "CurrentPrimaryHCP", "Comments",
//            "NextOfKin", "NextOfKinRelationshipToPatient"}, 0);
            
            DefaultTableModel tbl = new DefaultTableModel (new String[]{"PatientID", "FirstName", "LastName", "PhoneNumber"}, 0);
            

            while(rs.next())
            {
                String PatientID = String.valueOf(rs.getInt("PatientID"));
                String FirstName = rs.getString("PtFirstName"); 
                String LastName = rs.getString("PtLastName"); 
                String PhoneNumber = rs.getString("PtHomePhone");
                String EmergencyNumber = rs.getString("EmergencyPhoneNumber");
//                String PrevLastName = rs.getString("PtPreviousLastName");
//                String HomeAddress = rs.getString("HomeAddress1");
//                String HomeState = rs.getString("HomeStateProvinceRegion");
//                String city = rs.getString("HomeCity");
//                String Zipcode = rs.getString("HomeZip");
//                String Country = rs.getString("Country");
//                String citizen = rs.getString("Citizenship");
//                String Emailaddress = rs.getString("EmailAddress");
//                String ssn = rs.getString("PtSSN");
//                String dob = rs.getString("DOB");             
//                String Gender = rs.getString("Gender");
//                String ethnicassociation = rs.getString("EthnicAssociation");
//                String maritalstatus = rs.getString("MaritalStatus");
//                String CPHCP = rs.getString("CurrentPrimaryHCP");
//                String com = rs.getString("Comments");
//                String NextOfKin = rs.getString("NextOfKin");
//                String NextOfKinRelationshipToPatient = rs.getString("NextOfKinRelationshipToPatient");
                
//                String tbData[] = {PatientID, FirstName, LastName, PhoneNumber,
//                    EmergencyNumber, PrevLastName, HomeAddress, HomeState, city, 
//                    Zipcode, Country, citizen, Emailaddress, ssn, dob, Gender, ethnicassociation,
//                    maritalstatus, CPHCP, com, NextOfKin, NextOfKinRelationshipToPatient};

                String tbData[] = {PatientID, FirstName, LastName, PhoneNumber};
                tbl.addRow(tbData);
            }
            jTable1.setModel(tbl);
            conn.close();
        }
        catch(Exception e)
        {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnShowDataActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        btnContinue.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnShowData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tbLastName;
    // End of variables declaration//GEN-END:variables
}
